/************************************************************
  Windy1 USB Host Synth for Wind controllers
        MIT license
        Copyright (c) 2021 Tim King

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

****************************************************************/

#ifndef patches_h_
#define patches_h_

#define NUMBER_OF_PATCHES 100

#define PATCH_STRING_SYSPOS 0x0C
#define PATCH_STRING_LENGTH 31
#define NRPN_MSB_OSC1_SYSPOS 0x2C
#define NRPN_MSB_OSC1 64
#define NRPN_MSB_OSC1_LENGTH 18
#define NRPN_MSB_OSC2_SYSPOS 0x41
#define NRPN_MSB_OSC2 65
#define NRPN_MSB_OSC2_LENGTH 18
#define NRPN_MSB_OSC_FILT1_SYSPOS 0x56
#define NRPN_MSB_OSC_FILT1 72
#define NRPN_MSB_OSC_FILT1_LENGTH 12
#define NRPN_MSB_OSC_FILT2_SYSPOS 0x65
#define NRPN_MSB_OSC_FILT2 73
#define NRPN_MSB_OSC_FILT2_LENGTH 12
#define NRPN_MSB_NOISE_FILT3_SYSPOS 0x74
#define NRPN_MSB_NOISE_FILT3 74
#define NRPN_MSB_NOISE_FILT3_LENGTH 12
#define NRPN_MSB_NOISE_FILT4_SYSPOS 0x83
#define NRPN_MSB_NOISE_FILT4 75
#define NRPN_MSB_NOISE_FILT4_LENGTH 12
#define NRPN_MSB_SPARE_SYSPOS 0x92
#define NRPN_MSB_SPARE  79
#define NRPN_MSB_SPARE_LENGTH 3
#define NRPN_MSB_NOISE_SYSPOS 0x98
#define NRPN_MSB_NOISE  80
#define NRPN_MSB_NOISE_LENGTH 3 
#define NRPN_MSB_COMMON1_SYSPOS 0x9E
#define NRPN_MSB_COMMON1 81
#define NRPN_MSB_COMMON1_LENGTH 10
#define NRPN_MSB_COMMON2_SYSPOS 0xAB
#define NRPN_MSB_COMMON2 88
#define NRPN_MSB_COMMON2_LENGTH 3
#define NRPN_MSB_CHORUS_SYSPOS 0xB1
#define NRPN_MSB_CHORUS 112
#define NRPN_MSB_CHORUS_LENGTH 9
#define NRPN_MSB_DELAY_SYSPOS 0xBD
#define NRPN_MSB_DELAY 113
#define NRPN_MSB_DELAY_LENGTH 5
#define NRPN_MSB_REVERB_SYSPOS 0xC5
#define NRPN_MSB_REVERB 114
#define NRPN_MSB_REVERB_LENGTH 5 



#define CCOCTOSC1 0
#define CCSEMIOSC1 1
#define CCFINEOSC1 2
#define CCBEATOSC1 3
#define CCSAWOSC1 5
#define CCTRIOSC1 6
#define CCPULSEOSC1 7
#define CCPWOSC1 8
#define CCPWMFREQOSC1 9
#define CCPWMDEPTHOSC1 10
#define CCSWEEPDEPTHOSC1 11
#define CCSWEEPTIMEOSC1 12
#define CCBREATHDEPTHOSC1 13
#define CCBREATHATTAINOSC1 14
#define CCBREATHCURVEOSC1 15
#define CCBREATHTHRESHOSC1 16
#define CCLEVELOSC1 17
#define CCOCTOSC2 0
#define CCSEMIOSC2 1
#define CCFINEOSC2 2
#define CCBEATOSC2 3
#define CCSAWOSC2 5
#define CCTRIOSC2 6
#define CCPULSEOSC2 7
#define CCPWOSC2 8
#define CCPWMFREQOSC2 9
#define CCPWMDEPTHOSC2 10
#define CCSWEEPDEPTHOSC2 11
#define CCSWEEPTIMEOSC2 12
#define CCBREATHDEPTHOSC2 13
#define CCBREATHATTAINOSC2 14
#define CCBREATHCURVEOSC2 15
#define CCBREATHTHRESHOSC2 16
#define CCLEVELOSC2 17
#define CCMODEOSCFILTER1 0
#define CCFREQOSCFILTER1 1
#define CCQFACTOROSCFILTER1 2
#define CCKEYFOLLOWOSCFILTER1 3
#define CCBREATHMODOSCFILTER1 4
#define CCLFOFREQOSCFILTER1 5
#define CCLFODEPTHOSCFILTER1 6
#define CCLFOBREATHOSCFILTER1 7
#define CCLFOTHRESHOSCFILTER1 8
#define CCSWEEPDEPTHOSCFILTER1 9
#define CCSWEEPTIMEOSCFILTER1 10
#define CCBREATHCURVEOSCFILTER1 11
#define CCMODEOSCFILTER2 0
#define CCFREQOSCFILTER2 1
#define CCQFACTOROSCFILTER2 2
#define CCKEYFOLLOWOSCFILTER2 3
#define CCBREATHMODOSCFILTER2 4
#define CCLFOFREQOSCFILTER2 5
#define CCLFODEPTHOSCFILTER2 6
#define CCLFOBREATHOSCFILTER2 7
#define CCLFOTHRESHOSCFILTER2 8
#define CCSWEEPDEPTHOSCFILTER2 9
#define CCSWEEPTIMEOSCFILTER2 10
#define CCBREATHCURVEOSCFILTER2 11
#define CCMODENOISEFILTER3 0
#define CCFREQNOISEFILTER3 1
#define CCQFACTORNOISEFILTER3 2
#define CCKEYFOLLOWNOISEFILTER3 3
#define CCBREATHMODNOISEFILTER3 4
#define CCLFOFREQNOISEFILTER3 5
#define CCLFODEPTHNOISEFILTER3 6
#define CCLFOBREATHNOISEFILTER3 7
#define CCLFOTHRESHNOISEFILTER3 8
#define CCSWEEPDEPTHNOISEFILTER3 9
#define CCSWEEPTIMENOISEFILTER3 10
#define CCBREATHCURVENOISEFILTER3 11
#define CCMODENOISEFILTER4 0
#define CCFREQNOISEFILTER4 1
#define CCQFACTORNOISEFILTER4 2
#define CCKEYFOLLOWNOISEFILTER4 3
#define CCBREATHMODNOISEFILTER4 4
#define CCLFOFREQNOISEFILTER4 5
#define CCLFODEPTHNOISEFILTER4 6
#define CCLFOBREATHNOISEFILTER4 7
#define CCLFOTHRESHNOISEFILTER4 8
#define CCSWEEPDEPTHNOISEFILTER4 9
#define CCSWEEPTIMENOISEFILTER4 10
#define CCBREATHCURVENOISEFILTER4 11
#define CCNOISETIME 0
#define CCNOISEBREATHCURVE 1
#define CCNOISELEVEL 2
#define CCBENDRANGE 0
#define CCBENDSTEP 1
#define CCVIBRATOPITCH 2
#define CCLINKOSCFILTERS 3
#define CCLINKNOISEFILTERS 4
#define CCFORMANT 5
#define CCXFADE 6
#define CCKEYTRIGGER 7
#define CC81_8 8
#define CCCHORUSON 9
#define CCVIBRATOAMP 0
#define CCAMPLEVEL 1
#define CCOCTBUTTONLEVEL 2
#define CCEFFECTSCHORUSDELAY1 0
#define CCEFFECTSCHORUSMOD1 1
#define CCEFFECTSCHORUSWET1 2
#define CCEFFECTSCHORUSDELAY2 3
#define CCEFFECTSCHORUSMOD2 4
#define CCEFFECTSCHORUSWET2 5
#define CCEFFECTSCHORUSFEEDBACK 6
#define CCEFFECTSCHORUSLFOFREQ 7
#define CCEFFECTSCHORUSDRYLEVEL 8
#define CCEFFECTSDELAYTIME 0
#define CCEFFECTSDELAYFEEDBACK 1
#define CCEFFECTSDELAYDAMP 2
#define CCEFFECTSDELAYLEVEL 3
#define CCEFFECTSDELAYSPARE 4
#define CCEFFECTSREVERBSPARE 0
#define CCEFFECTSREVERBLEVEL 1
#define CCEFFECTSREVERBDENSEEARLY 2
#define CCEFFECTSREVERBTIME 3
#define CCEFFECTSREVERBDAMP 4


typedef struct __attribute__((packed)) Patch{
    char patch_string[32]; 
    uint8_t nrpn_msb_osc1[NRPN_MSB_OSC1_LENGTH];
    uint8_t nrpn_msb_osc2[NRPN_MSB_OSC2_LENGTH];
    uint8_t nrpn_msb_osc_filt1[NRPN_MSB_OSC_FILT1_LENGTH];
    uint8_t nrpn_msb_osc_filt2[NRPN_MSB_OSC_FILT2_LENGTH];
    uint8_t nrpn_msb_noise_filt3[NRPN_MSB_NOISE_FILT3_LENGTH];
    uint8_t nrpn_msb_noise_filt4[NRPN_MSB_NOISE_FILT4_LENGTH];
    uint8_t nrpn_msb_spare[NRPN_MSB_SPARE_LENGTH];
    uint8_t nrpn_msb_noise[NRPN_MSB_NOISE_LENGTH];
    uint8_t nrpn_msb_common1[NRPN_MSB_COMMON1_LENGTH];
    uint8_t nrpn_msb_common2[NRPN_MSB_COMMON2_LENGTH];
    uint8_t nrpn_msb_chorus[NRPN_MSB_CHORUS_LENGTH];  // 9 
    uint8_t nrpn_msb_delay[NRPN_MSB_DELAY_LENGTH];    // 5 
    uint8_t nrpn_msb_reverb[NRPN_MSB_REVERB_LENGTH];   // 5
} patch_t;





#endif
