; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = windy1_teensy41

[env:windy1_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -D USB_MIDI_SERIAL
    -D ENABLE_LINE_IN=0
; Set the USB type to Serial + MIDI
;board_build.usb_type = serial_midi
build_src_filter =
    +<*>
    -<3rdparty/>
    -<scratch/>
    -<TestSketches/>
    -<build/>
    -<docs/>
lib_extra_dirs =
    3rdparty
lib_deps =
    olikraus/U8g2@^2.27.11

[env:windy1_teensy41_debug]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -D USB_MIDI_SERIAL
    -D ENABLE_LINE_IN=0
    -D DEBUG_USB_SERIAL
    -D DEBUG_MIDI_INPUT
    -D MIDI_DEBUG_LEVEL=2
    -D MIDI_DEBUG_RATE_MS=200
; Set the USB type to Serial + MIDI
;board_build.usb_type = serial_midi
build_src_filter =
    +<*>
    -<3rdparty/>
    -<scratch/>
    -<TestSketches/>
    -<build/>
    -<docs/>
lib_extra_dirs =
    3rdparty
lib_deps =
    olikraus/U8g2@^2.27.11

[env:windy1_teensy41_linein]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -D USB_MIDI_SERIAL
    -D ENABLE_LINE_IN=1
; Set the USB type to Serial + MIDI
;board_build.usb_type = serial_midi
build_src_filter =
    +<*>
    -<3rdparty/>
    -<scratch/>
    -<TestSketches/>
    -<build/>
    -<docs/>
lib_extra_dirs =
    3rdparty
lib_deps =
    olikraus/U8g2@^2.27.11

